[tool.poetry]
name = "show-forecasts"
version = "0.2.3"
description = "cGAN forecasts post-processing and visualization scripts"
authors = [
    "Fenwick <fenwick.cooper@physics.ox.ac.uk>",
    "Jason <Jason.Kinyua@igad.int>",
]
license = "CC BY 4.0"
readme = "README.md"
packages = [{ include = "show_forecasts", from = "./" }]
include = [{ path = "show_forecasts/data", format = ["sdist", "wheel"] }]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = "1.23.5"
pandas = "2.1"
Cartopy = "^0.24.1"
matplotlib = "^3.9.2"
cfgrib = "^0.9.10.4"
xarray = "2024.1.0"
eccodes = "^2.39.1"
netcdf4 = "^1.7.2"
pyshp = "^2.3.1"
ipykernel = "^6.29.5"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
